runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.7

# The settings below are to reduce costs during testing
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10
